"use client";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

// export const metadata = {
//   title: "AniFlix",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
